name: metzki
favicon: null
layout_spectrum: 0.09694
typography_spectrum: 0.59329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b11016'
    - '#373737'
    - '#e1a5a7'
  brandStrength: 0
  lightness: 0.5530924207996577
  saturation: 0.6679353946819901
  rhythmicContrast: 0.11071754386648536
purpose: []
