name: metzki
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59329
title: A digital artist in London
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d0d1d3'
    - '#363837'
    - '#929395'
    - '#831918'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
